version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "🤖 Dependencies"
    schedule:
      interval: weekly
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    labels:
     - "🤖 Dependencies"
