name: my service job
tasks:
  - name: my service task
    image: node:14
    run: |
      node server.js
    ports: 
      - port: 8080
    files:
      server.js: |
        const http = require('http');
        const hostname = '0.0.0.0';
        const port = 8080;
        const server = http.createServer((req, res) => {
          res.statusCode = 200;
          res.setHeader('Content-Type', 'text/plain');
          res.end('Hello World\n');
        });
        server.listen(port, hostname, () => {
          console.log(`Server running at http://${hostname}:${port}/`);
        });